### ISSUE TITLE
1.18.2 Purpur bug when game starts and errors pop up, players dont go to playzone and floor doesnt refresh

### ISSUE THREAD

**Issue by WataLaker37821** [Leon167/BlockParty-2.0#58]
**To Reproduce**
1. Go to arena 
2. select song and wait until game starts
3. Game will not drop you to playzone, and will not change floors
4. See error: [14:28:53 WARN]: [BlockParty] Task #2702 for BlockParty v2.0.5-RELEASE generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getType()" because "this.currentBlock" is null
	at de.leonkoth.blockparty.floor.Floor.removeBlocks(Floor.java:199) ~[BlockParty-2.0.5-RELEASE.jar:?]
	at de.leonkoth.blockparty.phase.GamePhase.run(GamePhase.java:157) ~[BlockParty-2.0.5-RELEASE.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Expected behavior**
Game supposed to start normally and let players to playzone and refresh floors

**Environment):**
 - Server version: [Purpur 1.18.2 last version]
 - BlockParty version [2.0.3.4]
 - Additional Plugins [ Plugins (66): AdvancedBan, AntiWorldFly, AuctionHouse, AuthMe, BlockParty, ChatEx, ChestShop, Chunky, Citizens, ClearLag, ClientDetector, CommandNPC, CrackShot, CrazyCrates, CreativeManager, DecentHolograms, DeluxeMenus, DiceFurniture, dynmap, Dynmap-WorldGuard, EasyPayments, Elevator, Essentials, EssentialsDiscord, EssentialsSpawn, FurnitureLib, GSit, HeadDatabase, ItemJoin, LibsDisguises, LuckPerms, Matrix, MobArena, MOTD, Multiverse-Core, NametagEdit, nAntiBot, NBTAPI, NoCheatPlus, NoteBlockAPI, PlaceholderAPI, PlayerKits, ProCasino, ProtectionLib, ProtocolLib, PvPToggle, QualityArmory, Quests, Roulette, SayFormat, Sentinel, ServerSigns, Shopkeepers, SkinsRestorer, spark, SpleefX, TAB, Vault, VirtualBooks, VoidGen, WGExtender, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, XProtect*]

**Comment by WataLaker37821** [comment]
i found that when i set songmanager songs and use noteblock songs game provides this bug
when i disable noteblock songs it becomes normal
